name: kw-linux

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ci-kw-linux
    if: ${{ github.repository != 'intel/pcm' }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: kw
      run: |
        mkdir build
        cd build
        cmake ..
        ci-kw-linux.sh "echo No Preparation" "make -j"
